# Generated by Django 6.0.5 on 2026-06-10 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telehealthsession',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telehealth_sessions_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telehealthsession',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telehealth_sessions_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telehealthsession',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telehealthsession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WAITING_ROOM', 'Waiting Room'), ('WAITING_FOR_DOCTOR', 'Waiting For Doctor'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=50),
        ),
    ]
