# Generated by Django 6.0.5 on 2026-06-10 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('RESOLVED', 'Resolved'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('TELEHEALTH_COMPLETED', 'Telehealth Completed'), ('NO_RESPONSE', 'No Response'), ('DUPLICATE', 'Duplicate'), ('ESCALATED_ELSEWHERE', 'Escalated Elsewhere')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('SYSTEM', 'System')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_AGENT', 'Waiting for Agent'), ('AGENT_ACTIVE', 'Agent Active'), ('WAITING_FOR_DOCTOR', 'Waiting for Doctor'), ('DOCTOR_ACTIVE', 'Doctor Active'), ('CLOSED', 'Closed')], default='WAITING_FOR_AGENT', max_length=50),
        ),
        migrations.CreateModel(
            name='ConversationAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations_history', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='messaging.conversation')),
                ('new_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_assigned_doctor_history', to=settings.AUTH_USER_MODEL)),
                ('previous_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assigned_doctor_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
        ),
    ]
