# Generated by Django 6.0.5 on 2026-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin'), ('VOLUNTEER', 'Volunteer'), ('DONOR', 'Donor'), ('AGENT', 'Agent')], default='PATIENT', max_length=50),
        ),
    ]
