# Generated by Django 6.0.5 on 2026-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('OPTICIAN', 'Optician'), ('MEDICAL_AGENT', 'Medical Agent'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin'), ('VOLUNTEER', 'Volunteer'), ('DONOR', 'Donor'), ('AGENT', 'Agent')], default='PATIENT', max_length=50),
        ),
    ]
