# Generated by Django 6.0.5 on 2026-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_date_of_birth_user_gender_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('OPTICIAN', 'Optician'), ('MEDICAL_AGENT', 'Medical Agent'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin'), ('VOLUNTEER', 'Volunteer'), ('DONOR', 'Donor'), ('AGENT', 'Agent')], default='PATIENT', max_length=50),
        ),
    ]
