# Generated by Django 6.0.5 on 2026-06-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('medical_records', '0002_consultationencounter_clinical_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eyewear_prescriptions', to='medical_records.consultationencounter'),
        ),
    ]
