# Generated by Django 6.0.5 on 2026-06-28 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_prescription_encounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='flash_sales', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Flash Sale',
                'verbose_name_plural': 'Flash Sales',
            },
        ),
    ]
