# Generated by Django 6.0.5 on 2026-07-26 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_flash_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderFieldConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(choices=[('SPH', 'Sphere (SPH)'), ('CYL', 'Cylinder (CYL)'), ('AXIS', 'Axis'), ('ADD', 'Addition (ADD)'), ('PUPILLARY_DISTANCE', 'Pupillary Distance (PD)'), ('NEAR_PD', 'Near PD'), ('SEGMENT_HEIGHT', 'Segment Height'), ('FITTING_HEIGHT', 'Fitting Height')], max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='LensRecommendationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('metric', models.CharField(choices=[('SPH', 'Sphere (strongest eye)'), ('CYL', 'Cylinder (strongest eye)'), ('ADD', 'Addition (strongest eye)'), ('PD', 'Pupillary Distance')], max_length=10)),
                ('operator', models.CharField(choices=[('GTE', '≥'), ('LTE', '≤'), ('GT', '>'), ('LT', '<'), ('BETWEEN', 'between'), ('EQ', '=')], default='GTE', max_length=10)),
                ('use_absolute', models.BooleanField(default=True, help_text='Compare the absolute value (SPH/CYL are often negative).')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound — only used with the "between" operator.', max_digits=6, null=True)),
                ('action', models.CharField(choices=[('RECOMMEND', 'Recommend (highlight)'), ('RESTRICT', 'Restrict (only allow these)'), ('HIDE', 'Hide (remove these)')], default='RECOMMEND', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional note shown to the patient when this rule matches.')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower numbers evaluate first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_lens_options', models.ManyToManyField(blank=True, related_name='recommendation_rules', to='ecommerce.lensoption')),
                ('target_lens_types', models.ManyToManyField(blank=True, related_name='recommendation_rules', to='ecommerce.lenstype')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
