# Generated by Django 6.0.5 on 2026-07-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_builderfieldconfig_lensrecommendationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderfieldconfig',
            name='input_type',
            field=models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('SELECT', 'Dropdown')], default='NUMBER', max_length=10),
        ),
        migrations.AddField(
            model_name='builderfieldconfig',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='builderfieldconfig',
            name='select_options',
            field=models.JSONField(blank=True, default=list, help_text='Choices for a dropdown field.'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='extra_measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='builderfieldconfig',
            name='field_key',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='lensrecommendationrule',
            name='metric',
            field=models.CharField(max_length=60),
        ),
    ]
