# Generated by Django 6.0.5 on 2026-07-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_builderfieldconfig_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='bridge_width',
            field=models.PositiveIntegerField(blank=True, help_text='Bridge / nose width, mm', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='features',
            field=models.TextField(blank=True, help_text='e.g. Spring hinges, Adjustable nose pads (comma-separated)'),
        ),
        migrations.AddField(
            model_name='frame',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('UNISEX', 'Unisex'), ('KIDS', 'Kids')], default='UNISEX', max_length=10),
        ),
        migrations.AddField(
            model_name='frame',
            name='lens_height',
            field=models.PositiveIntegerField(blank=True, help_text='Lens height, mm', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='lens_width',
            field=models.PositiveIntegerField(blank=True, help_text='Lens width (eye size), mm', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='rim_type',
            field=models.CharField(choices=[('FULL_RIM', 'Full Rim'), ('SEMI_RIMLESS', 'Semi-Rimless'), ('RIMLESS', 'Rimless')], default='FULL_RIM', max_length=15),
        ),
        migrations.AddField(
            model_name='frame',
            name='size_category',
            field=models.CharField(choices=[('NARROW', 'Narrow'), ('MEDIUM', 'Medium'), ('WIDE', 'Wide')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='frame',
            name='temple_length',
            field=models.PositiveIntegerField(blank=True, help_text='Temple (arm) length, mm', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='total_width',
            field=models.PositiveIntegerField(blank=True, help_text='Total frame width, mm', null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Frame weight, grams', null=True),
        ),
    ]
