# Generated by Django 6.0.5 on 2026-07-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_frame_bridge_width_frame_description_frame_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
