# Generated by Django 6.0.5 on 2026-05-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile_emergency_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
