# Generated by Django 6.0.5 on 2026-05-22 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientprofile_patient_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(choices=[('OPTOMETRIST', 'Optometrist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENT', 'ENT Specialist'), ('GENERAL_PRACTITIONER', 'General Practitioner')], max_length=50)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('max_daily_appointments', models.PositiveIntegerField(default=15)),
                ('avatar', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
