# Generated by Django 6.0.5 on 2026-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctorprofile_accepts_telehealth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='max_active_conversations',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='max_active_telehealth_sessions',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
