# Generated by Django 6.0.5 on 2026-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctorprofile_max_active_conversations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
