# Generated by Django 6.0.5 on 2026-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_delivery_address_to_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='delivery_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
