# Generated by Django 6.0.5 on 2026-07-22 21:04

from django.db import migrations

DEPARTMENTS = [
    'Administration',
    'Billing & Finance',
    'Consultants',
    'Emergency',
    'Laboratory',
    'Ophthalmology',
    'Optometry',
    'Patient Care',
    'Pharmacy',
    'Physiotherapy',
    'Radiology',
    'Reception',
    'Surgery',
    'Telehealth',
]


def seed_departments(apps, schema_editor):
    Department = apps.get_model('users', 'Department')
    for name in DEPARTMENTS:
        Department.objects.get_or_create(name=name, defaults={'is_active': True})


def unseed_departments(apps, schema_editor):
    pass  # keep data on rollback


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_department_and_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_departments, unseed_departments),
    ]
