# Generated by Django 6.0.5 on 2026-06-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_service_billing_and_plan'),
        ('payments', '0002_paymenttransaction_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='appointments.appointment'),
        ),
    ]
