# Generated by Django 6.0.5 on 2026-08-13 01:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_appointment_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_txn_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('MONNIFY', 'Monnify'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('MONNIFY', 'Monnify'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20)),
                ('mode', models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], default='TEST', max_length=10)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('client_key', models.CharField(blank=True, default='', max_length=255)),
                ('secret_key_encrypted', models.TextField(blank=True, default='')),
                ('contract_code', models.CharField(blank=True, default='', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'mode'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'mode'), name='unique_gateway_provider_mode')],
            },
        ),
    ]
