# Generated by Django 6.0.5 on 2026-08-13 01:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_provider_txn_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('MONNIFY', 'Monnify'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('event_hash', models.CharField(max_length=128)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_hash'), name='unique_webhook_provider_event')],
            },
        ),
    ]
