# Generated by Django 6.0.5 on 2026-10-03 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=150)),
                ('donor_email', models.EmailField(max_length=254)),
                ('currency', models.CharField(choices=[('NGN', 'Naira'), ('GBP', 'Pound sterling'), ('USD', 'US dollar')], default='NGN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('ANNUAL', 'Annually (yearly reminder)')], default='ONE_TIME', max_length=10)),
                ('purpose', models.CharField(choices=[('TEST', 'Sponsor a test'), ('INTERVENTION', 'Sponsor an intervention'), ('GENERAL', 'General donation')], default='GENERAL', max_length=15)),
                ('dedicated_to', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting payment'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('next_reminder_on', models.DateField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='donations_d_status_ad9788_idx'), models.Index(fields=['frequency', 'next_reminder_on'], name='donations_d_frequen_22c303_idx'), models.Index(fields=['donor_email'], name='donations_d_donor_e_914ea9_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('GP', 'GP'), ('NURSE', 'Nurse'), ('NUTRITIONIST', 'Nutritionist')], max_length=15)),
                ('session_format', models.CharField(choices=[('4x15', '4 × 15-minute consultations'), ('3x20', '3 × 20-minute consultations')], default='4x15', max_length=4)),
                ('registration_number', models.CharField(blank=True, help_text='Professional registration or licence number, if the applicant gave one.', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='NEW', max_length=10)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='donations_v_status_d5cc46_idx')],
            },
        ),
    ]
