# Generated by Django 6.0.5 on 2026-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_faq_heroslide_sitesettings_teammember_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='NaderkEye Care', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
