# Generated by Django 6.0.5 on 2026-07-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_add_favicon_url_to_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Naderkela', max_length=150),
        ),
    ]
