# Generated by Django 6.0.5 on 2026-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_sitesettings_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About'), ('laboratory', 'Laboratory'), ('telehealth', 'Telehealth'), ('optical_store', 'Optical Store'), ('contact', 'Contact'), ('home', 'Home')], max_length=40)),
                ('section_key', models.CharField(max_length=60)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'order'],
                'constraints': [models.UniqueConstraint(fields=('page', 'section_key'), name='unique_page_section')],
            },
        ),
    ]
