# Generated by Django 6.0.5 on 2026-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_pagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('laboratory', 'Laboratory'), ('telehealth', 'Telehealth'), ('optical_store', 'Optical Store'), ('contact', 'Contact'), ('home', 'Home'), ('extend_life_africa', 'Extend Life Africa')], max_length=40),
        ),
    ]
