# Generated by Django 6.0.5 on 2026-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_cancelled_at_appointment_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('TELEHEALTH', 'Telehealth'), ('HOME_VISIT', 'Home Visit'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency')], default='PHYSICAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('NO_SHOW', 'Missed')], default='PENDING', max_length=50),
        ),
    ]
