# Generated by Django 6.0.5 on 2026-06-26 11:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_appointment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='billing_type',
            field=models.CharField(choices=[('PER_VISIT', 'Per Visit'), ('MONTHLY', 'Monthly (unlimited sessions)'), ('SESSION_PACK', 'Session Pack (N sessions per payment)')], default='PER_VISIT', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='sessions_included',
            field=models.PositiveIntegerField(blank=True, help_text='SESSION_PACK only — number of sessions per payment', null=True),
        ),
        migrations.CreateModel(
            name='PatientServicePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(max_length=255)),
                ('sessions_purchased', models.PositiveIntegerField(default=1)),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_plans', to='appointments.medicalservice')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'service', 'is_active'], name='appointment_patient_2c054f_idx')],
            },
        ),
    ]
