# Generated by Django 6.0.5 on 2026-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_medicalservice_available_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='available_online',
            field=models.BooleanField(default=False, help_text='If True and requires_doctor is True, patients can choose physical or telehealth. Ignored for facility-based services.'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='required_specialization',
            field=models.CharField(blank=True, choices=[('OPTOMETRIST', 'Optometrist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENT', 'ENT Specialist'), ('GENERAL_PRACTITIONER', 'General Practitioner')], help_text='Only relevant when requires_doctor is True', max_length=50, null=True),
        ),
    ]
