# Generated by Django 6.0.5 on 2026-07-27 07:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_facility_bookings_nullable_doctor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicalservice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_medicalservice_name_ci'),
        ),
    ]
