# Generated by Django 6.0.5 on 2026-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_medicalservice_unique_medicalservice_name_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='required_specialization',
            field=models.CharField(blank=True, help_text='Specialization code a doctor must hold. Only relevant when requires_doctor is True', max_length=50, null=True),
        ),
    ]
